services:
  - type: web
    name: face-detection-backend
    env: python
    region: ohio
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    plan: free
    autoDeploy: false

  - type: web
    name: face-detection-frontend
    env: static
    buildCommand: cd web-dashboard && npm install && npm run build
    staticPublishPath: web-dashboard/dist
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: face-detection-backend
          property: url

